name: k8s
description: Runs your build step as a kubernetes job
author: https://github.com/dln
requirements:
- jq
- jsonnet
- kubectl
configuration:
  properties:
    image:
      type: string
    always-pull:
      type: boolean
    command:
      type: array
    entrypoint:
      type: array
    environment:
      type: array
    environment-from-secret:
      type: [string, array]
    init-environment-from-secret:
      type: [string, array]
    init-image:
      type: string
    mount-hostpath:
      type: [string, array]
    mount-secret:
      type: [string, array]
    privileged:
      type: boolean
    job-ttl-seconds-after-finished:
      type: number
    secret-name:
      type: string
    git-credentials-secret-name:
      type: string
    git-credentials-secret-key:
      type: string
    git-ssh-secret-name:
      type: string
    git-ssh-secret-key:
      type: string
    agent-token-secret-key:
      type: string
    default-secret-name:
      type: string
    build-path-host-path:
      type: string
    build-path-pvc:
      type: string
    git-mirrors-host-path:
      type: string
    workdir:
      type: string
    patch:
      type: string
    resources-request-cpu:
      type: string
    resources-limit-cpu:
      type: string
    resources-request-memory:
      type: string
    resources-limit-memory:
      type: string
    use-agent-node-affinity:
      type: boolean
  required:
  - image
  additionalProperties: false
