steps:
  - name: shellcheck hooks
    agents:
      queue: default
      os: linux
    command:
      - echo "Running shellcheck"
      - shellcheck hooks/*
    plugins:
      - EmbarkStudios/k8s#1.2.6:
          image: koalaman/shellcheck-alpine
          default-secret-name: buildkite-k8s-plugin
          use-agent-node-affinity: true
  - wait
  - name: Build and publish k8s-buildkite-agent container image
    branches: 'master'
    agents:
      queue: monorepo-ci
      os: linux
    plugins:
      - EmbarkStudios/k8s#1.2.6:
          image: gcr.io/kaniko-project/executor:latest
          default-secret-name: buildkite-k8s-plugin
          use-agent-node-affinity: true
          command:
            - --destination=embarkstudios/k8s-buildkite-agent
            - --context=.
            - --reproducible
            - --cache=true
            - --cache-repo=kaniko-cache.buildkite.svc.cluster.local/kaniko/cache
            - --cache-dir=$BUILDKITE_BUILD_PATH/_kaniko_cache
          mount-secret:
            - docker-hub-credentials:/kaniko/.docker
