#!/bin/bash

set -euo pipefail

basedir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

job_name="${BUILDKITE_PIPELINE_SLUG}-${BUILDKITE_BUILD_NUMBER}-$(head -c 5 /dev/urandom | base32 | tr '[:upper:]' '[:lower:]')"
echo "${job_name}" > /tmp/job_name

if [[ ${BUILDKITE_TIMEOUT:-"false"} == "false" ]]; then
  BUILDKITE_TIMEOUT=600
fi
((timeout=BUILDKITE_TIMEOUT*60))
export BUILDKITE_TIMEOUT

readonly job_apply_loop_interval_seconds="${K8S_PLUGIN_JOB_APPLY_LOOP_INTERVAL:-5}"
readonly job_apply_loop_timeout_seconds="${K8S_PLUGIN_JOB_APPLY_LOOP_TIMEOUT:-120}"
readonly log_loop_interval_seconds="${K8S_PLUGIN_LOG_LOOP_INTERVAL:-3}"
readonly job_status_loop_sleep_interval="${K8S_PLUGIN_JOB_STATUS_LOOP_INTERVAL:-5}"
readonly cleanup_old_jobs_loop_interval_seconds="${K8S_PLUGIN_CLEANUP_OLD_JOBS_LOOP_INTERVAL:-5}"
readonly cleanup_old_jobs_loop_timeout_seconds="${K8S_PLUGIN_CLEANUP_OLD_JOBS_LOOP_INTERVAL:-2}"

readonly job_json="$(mktemp)"
readonly job_log_complete_marker_file="$(mktemp)"

function cleanup {
  # Delete all jobs older than a day
  local -r cleanup_start_time="$SECONDS"
  local cleanup_old_jobs_exit_code=""

  while [[ "$((SECONDS - cleanup_start_time))" -lt "$cleanup_old_jobs_loop_timeout_seconds" ]]
  do
    set +e
    local old_jobs="$(kubectl get job -l buildkite/plugin=k8s | awk 'match($4,/[0-9]+d/) {print $1}')"
    if [[ -n "$old_jobs" ]]; then
      kubectl delete job "$old_jobs"
    fi
    cleanup_old_jobs_exit_code="$?"
    set -e

    if [[ "$cleanup_old_jobs_exit_code" == "0" ]]; then
      break
    else
      echo "Attempt to cleanup old jobs failed, exit code '$cleanup_old_jobs_exit_code'"
      sleep "$cleanup_old_jobs_loop_interval_seconds"
    fi
  done

  echo "Cleanup old jobs exit code '$cleanup_old_jobs_exit_code'"
  rm -f "$job_json" "$job_log_complete_marker_file"
}
trap cleanup EXIT

function tail_logs {
  local log_snapshot=""
  # Once logs are not empty we start attempting to stream them.
  # Keep looping otherwise since empty output means that there is no useful log to display so we're not losing information by looping.
  while true;
  do
    set +e
    log_snapshot="$(timeout 5 kubectl logs --limit-bytes 1024 "job/${job_name}" 2>/dev/null)"
    set -e
    if [[ -n "$log_snapshot" ]]; then
      break
    fi
    sleep "$log_loop_interval_seconds"
  done

  # Run kubectl logs --follow in a loop since it can fail:
  #   1) It can fail due to pod not being initialized yet: "Error from server (BadRequest): container "step" in pod "somepod" is waiting to start: PodInitializing"
  #   2) It can fail mid-streaming, in this case we unfortunately will display logs multiple times (partially).
  #   3) It can hang not providing any result, that's why we check not only exit code but also contents in the loop above.
  while ! kubectl logs --follow "job/${job_name}" 2>/dev/null;
  do
    sleep "$log_loop_interval_seconds"
  done

  echo "0" > "$job_log_complete_marker_file"
}

echo "--- :kubernetes: Starting Kubernetes Job"

export patchFunc=${BUILDKITE_PLUGIN_K8S_PATCH:-"function(f) f"}

jsonnet \
  --tla-str "jobName=${job_name}" \
  --tla-str-file "stepEnvFile=${BUILDKITE_ENV_FILE}" \
  --tla-code "agentEnv=$(jq -c -n env)" \
  --tla-code patchFunc \
  "${basedir}/lib/job.jsonnet" \
  > "$job_json"

readonly job_apply_start_time="$SECONDS"
job_apply_exit_code=""

while [[ "$((SECONDS - job_apply_start_time))" -lt "$job_apply_loop_timeout_seconds" ]]
do
  set +e
  kubectl apply -f "$job_json"
  job_apply_exit_code="$?"
  set -e

  if [[ "$job_apply_exit_code" == "0" ]]; then
    break
  else
    echo "Attempt to schedule the job failed, exit code '$job_apply_exit_code'"
    sleep "$job_apply_loop_interval_seconds"
  fi
done
echo "Schedule job exit code '$job_apply_exit_code'"

echo "Timeout: ${timeout}s"

echo "+++ :kubernetes: Running image: ${BUILDKITE_PLUGIN_K8S_IMAGE}"

tail_logs &

counter=${timeout}
jobstatus=""
while [[ -z "$jobstatus" ]] ; do
  set +e
  jobstatus=$(kubectl get job "${job_name}" -o 'jsonpath={.status.conditions[].type}')
  set -e
  sleep "$job_status_loop_sleep_interval"
  if [[ $timeout -gt 0 ]]; then
    (( counter -= job_status_loop_sleep_interval )) || jobstatus="timeout"
  fi
done

echo "--- :kubernetes: Job status: $jobstatus"

# Wait for logs to be printed because printing runs in a fork and we're racing with it.
readonly log_wait_start_time="$SECONDS"
while [[ "$(cat "$job_log_complete_marker_file")" != "0" ]] && [[ "$((SECONDS - log_wait_start_time))" -lt 30 ]]
do
  sleep 0.5
done

status=1
if [[ "$jobstatus" == "Complete" ]] ; then
  echo "success"
  status=0
fi

exit $status
