#!/bin/bash

set -euo pipefail

if [[ $OSTYPE == darwin* ]]; then
  exit 0
fi

if [[ -v "BUILDKITE_PLUGIN_K8S_IS_JOB" ]]; then
	# do not recurse
	exit 0
fi

job_name="$(cat /tmp/job_name)"

echo "--- :kubernetes: Cleanup"

readonly job_cleanup_after_finished_via_plugin="${BUILDKITE_PLUGIN_K8S_JOB_CLEANUP_AFTER_FINISHED_VIA_PLUGIN:-}"
readonly job_cleanup_retry_sec="${BUILDKITE_PLUGIN_K8S_JOB_CLEANUP_RETRY_INTERVAL_SEC:-5}"
readonly job_cleanup_timeout_sec="${BUILDKITE_PLUGIN_K8S_JOB_CLEANUP_TIMEOUT_SEC:-60}"
readonly job_cleanup_start_time="$SECONDS"

external_secrets=${BUILDKITE_PLUGIN_K8S_EXTERNAL_SECRETS:-}
external_secrets_list=${BUILDKITE_PLUGIN_K8S_EXTERNAL_SECRETS_0:-}



# If External Secrets were used, clean them up
if [[ -n $external_secrets || -n $external_secrets_list ]]; then
  echo "Deleting ExternalSecrets"
  kubectl delete ExternalSecret "$job_name"
fi 

if [[ "$job_cleanup_after_finished_via_plugin" != "true" ]]; then
  exit 0
fi


job_cleanup_exit_code=""
while [[ "$((SECONDS - job_cleanup_start_time))" -lt "$job_cleanup_timeout_sec" ]]
do
  set +e
  pod=$(kubectl get pod --output=name -l "job-name=${job_name}")
  if [[ -n "${pod}" ]] ; then
    kubectl patch --patch '{"spec":{"activeDeadlineSeconds":1}}' "${pod}"
  fi
  kubectl patch --patch '{"spec":{"activeDeadlineSeconds":1}}' "job/${job_name}"
  job_cleanup_exit_code="$?"
  set -e

  if [[ "$job_cleanup_exit_code" == "0" ]]; then
    break
  else
    echo "Attempt to cleanup the job failed, exit code '$job_cleanup_exit_code'"
    sleep "$job_cleanup_retry_sec"
  fi
done

echo "Job cleanup exit code '$job_cleanup_exit_code'"
